[2024-02-12T22:53:20.076+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_taxi-load_to_pg.upload_to_pg manual__2024-02-12T22:53:19.040386+00:00 [queued]>
[2024-02-12T22:53:20.087+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_taxi-load_to_pg.upload_to_pg manual__2024-02-12T22:53:19.040386+00:00 [queued]>
[2024-02-12T22:53:20.087+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-12T22:53:20.101+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_pg> on 2024-02-12 22:53:19.040386+00:00
[2024-02-12T22:53:20.105+0000] {standard_task_runner.py:60} INFO - Started process 559 to run task
[2024-02-12T22:53:20.108+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ny_taxi-load_to_pg', 'upload_to_pg', 'manual__2024-02-12T22:53:19.040386+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dag_ny_taxi_load_to_pg.py', '--cfg-path', '/tmp/tmprzla2ic6']
[2024-02-12T22:53:20.109+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask upload_to_pg
[2024-02-12T22:53:20.155+0000] {task_command.py:423} INFO - Running <TaskInstance: ny_taxi-load_to_pg.upload_to_pg manual__2024-02-12T22:53:19.040386+00:00 [running]> on host 7b7b8b9b0fa9
[2024-02-12T22:53:20.224+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ny_taxi-load_to_pg' AIRFLOW_CTX_TASK_ID='upload_to_pg' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T22:53:19.040386+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-12T22:53:19.040386+00:00'
[2024-02-12T22:53:21.830+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/upload_to_pg.py", line 15, in upload_to_pg
    df = pd.read_csv(f"/mnt/ny_taxi/{file}")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 583, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 875, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 850, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas/_libs/parsers.pyx", line 2021, in pandas._libs.parsers.raise_parser_error
  File "/usr/local/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/local/lib/python3.8/gzip.py", line 498, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
[2024-02-12T22:53:21.850+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ny_taxi-load_to_pg, task_id=upload_to_pg, execution_date=20240212T225319, start_date=20240212T225320, end_date=20240212T225321
[2024-02-12T22:53:21.871+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 24 for task upload_to_pg (Compressed file ended before the end-of-stream marker was reached; 559)
[2024-02-12T22:53:21.888+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-12T22:53:21.917+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
