[2024-02-12T21:10:46.925+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:10:46.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:10:46.928+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:10:46.928+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:10:46.968+0000] {processor.py:840} INFO - DAG(s) 'ny_taxi-load_to_pg' retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:10:47.176+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:10:47.175+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:ny_taxi-load_to_pg
[2024-02-12T21:10:47.195+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:10:47.195+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:ny_taxi-load_to_pg
[2024-02-12T21:10:47.208+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:10:47.208+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:ny_taxi-load_to_pg
[2024-02-12T21:10:47.209+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:10:47.209+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T21:10:47.224+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:10:47.224+0000] {dag.py:3058} INFO - Creating ORM DAG for ny_taxi-load_to_pg
[2024-02-12T21:10:47.236+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:10:47.236+0000] {dag.py:3823} INFO - Setting next_dagrun for ny_taxi-load_to_pg to 2024-02-12 16:00:00+00:00, run_after=2024-02-12 20:00:00+00:00
[2024-02-12T21:10:47.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.348 seconds
[2024-02-12T21:10:55.359+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:10:55.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:10:55.362+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:10:55.362+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:10:55.398+0000] {processor.py:840} INFO - DAG(s) 'ny_taxi-load_to_pg' retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:10:55.410+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:10:55.410+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T21:10:55.433+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:10:55.433+0000] {dag.py:3823} INFO - Setting next_dagrun for ny_taxi-load_to_pg to 2024-02-12 16:00:00+00:00, run_after=2024-02-12 20:00:00+00:00
[2024-02-12T21:10:55.462+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.106 seconds
[2024-02-12T21:11:25.550+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:11:25.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:11:25.553+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:11:25.553+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:11:25.574+0000] {processor.py:840} INFO - DAG(s) 'ny_taxi-load_to_pg' retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:11:25.677+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:11:25.677+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T21:11:25.698+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:11:25.697+0000] {dag.py:3823} INFO - Setting next_dagrun for ny_taxi-load_to_pg to 2024-02-12 16:00:00+00:00, run_after=2024-02-12 20:00:00+00:00
[2024-02-12T21:11:25.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.172 seconds
[2024-02-12T21:11:42.763+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:11:42.764+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:11:42.766+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:11:42.765+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:11:42.800+0000] {processor.py:840} INFO - DAG(s) 'ny_taxi-load_to_pg' retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:11:42.812+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:11:42.812+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T21:11:42.824+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:11:42.824+0000] {dag.py:3823} INFO - Setting next_dagrun for ny_taxi-load_to_pg to None, run_after=None
[2024-02-12T21:11:42.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.092 seconds
[2024-02-12T21:12:13.030+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:12:13.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:12:13.033+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:12:13.033+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:12:13.056+0000] {processor.py:840} INFO - DAG(s) 'ny_taxi-load_to_pg' retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:12:13.183+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:12:13.183+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T21:12:13.193+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:12:13.192+0000] {dag.py:3823} INFO - Setting next_dagrun for ny_taxi-load_to_pg to None, run_after=None
[2024-02-12T21:12:13.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.191 seconds
[2024-02-12T21:12:39.200+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:12:39.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:12:39.202+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:12:39.202+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:12:39.229+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:12:39.225+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 21, in <module>
    download = PythonOperator()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-02-12T21:12:39.230+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:12:39.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.054 seconds
[2024-02-12T21:12:44.239+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:12:44.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:12:44.241+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:12:44.241+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:12:44.273+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:12:44.269+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 19, in <module>
    download = PythonOperator()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-02-12T21:12:44.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:12:44.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.060 seconds
[2024-02-12T21:13:14.497+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:13:14.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:13:14.500+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:13:14.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:13:14.525+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:13:14.520+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 19, in <module>
    download = PythonOperator()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-02-12T21:13:14.527+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:13:14.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.053 seconds
[2024-02-12T21:13:44.697+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:13:44.698+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:13:44.700+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:13:44.700+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:13:44.723+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:13:44.718+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 19, in <module>
    download = PythonOperator()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-02-12T21:13:44.725+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:13:44.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.045 seconds
[2024-02-12T21:14:14.917+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:14:14.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:14:14.919+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:14:14.919+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:14:14.938+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:14:14.933+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 19, in <module>
    download = PythonOperator()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-02-12T21:14:14.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:14:14.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.044 seconds
[2024-02-12T21:14:22.979+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:14:22.980+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:14:22.981+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:14:22.980+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:14:23.007+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:14:23.003+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 21, in <module>
    python_callable=download_data,
NameError: name 'download_data' is not defined
[2024-02-12T21:14:23.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:14:23.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.060 seconds
[2024-02-12T21:14:53.218+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:14:53.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:14:53.220+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:14:53.220+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:14:53.237+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:14:53.233+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 21, in <module>
    python_callable=download_data,
NameError: name 'download_data' is not defined
[2024-02-12T21:14:53.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:14:53.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.037 seconds
[2024-02-12T21:15:23.416+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:15:23.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:15:23.418+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:15:23.418+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:15:23.442+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:15:23.438+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 21, in <module>
    python_callable=download_data,
NameError: name 'download_data' is not defined
[2024-02-12T21:15:23.444+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:15:23.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.048 seconds
[2024-02-12T21:15:53.646+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:15:53.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:15:53.649+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:15:53.648+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:15:53.681+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:15:53.674+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 21, in <module>
    python_callable=download_data,
NameError: name 'download_data' is not defined
[2024-02-12T21:15:53.683+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:15:53.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.058 seconds
[2024-02-12T21:16:23.843+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:16:23.844+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:16:23.845+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:16:23.845+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:16:23.865+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:16:23.861+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 21, in <module>
    python_callable=download_data,
NameError: name 'download_data' is not defined
[2024-02-12T21:16:23.866+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:16:23.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.041 seconds
[2024-02-12T21:16:50.040+0000] {processor.py:161} INFO - Started process (PID=250) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:16:50.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:16:50.043+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:16:50.042+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:16:50.075+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:16:50.072+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 21, in <module>
    python_callable=download_data,
NameError: name 'download_data' is not defined
[2024-02-12T21:16:50.077+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:16:50.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.058 seconds
[2024-02-12T21:17:20.232+0000] {processor.py:161} INFO - Started process (PID=257) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:17:20.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:17:20.233+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:17:20.233+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:17:20.253+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:17:20.248+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 21, in <module>
    python_callable=download_data,
NameError: name 'download_data' is not defined
[2024-02-12T21:17:20.255+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:17:20.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.041 seconds
[2024-02-12T21:17:50.458+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:17:50.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:17:50.459+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:17:50.459+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:17:50.479+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:17:50.475+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 21, in <module>
    python_callable=download_data,
NameError: name 'download_data' is not defined
[2024-02-12T21:17:50.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:17:50.498+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.042 seconds
[2024-02-12T21:18:20.646+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:18:20.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_taxi_load_to_pg.py for tasks to queue
[2024-02-12T21:18:20.648+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:18:20.648+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:18:20.667+0000] {logging_mixin.py:188} INFO - [2024-02-12T21:18:20.663+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ny_taxi_load_to_pg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_taxi_load_to_pg.py", line 21, in <module>
    python_callable=download_data,
NameError: name 'download_data' is not defined
[2024-02-12T21:18:20.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_taxi_load_to_pg.py
[2024-02-12T21:18:20.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_taxi_load_to_pg.py took 0.046 seconds
